name: CAD Capgains CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry codecov tox flake8
        poetry install -v

    - name: Run tests
      run: |
        tox -e py
        flake8

# TODO: Go over Codecov setup and then re-enable
#    - name: Upload coverage to Codecov
#      env:
#        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#      run: |
#        codecov
#        bash <(curl -s https://codecov.io/bash)
